---
title: Aan de slag met Sonic Pi
hero_image: images/banner.png
description: Leer hoe je muziek live kunt coderen op de Raspberry Pi met Sonic Pi
original_url: https://raspberrypi.org/learning/getting-started-with-sonic-pi
theme: rood
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: muziek
technologies: sonic-pi
site_areas: projecten
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Eerste geluiden met Sonic Pi
  - 
    title: Herhaal een deuntje
    completion:
      - engaged
  - 
    title: MIDI-noten en muzieknoten
  - 
    title: Verander de geluiden
  - 
    title: Gebruik samples
  - 
    title: Twee liedjes tegelijkertijd spelen
  - 
    title: Live coderen!
  - 
    title: Effecten toevoegen
  - 
    title: Parameters wijzigen
  - 
    title: Gebruik van rrand
    completion:
      - internal
  - 
    title: Hoe nu verder?
