---
title: Sonic Pi के साथ शुरुआत करना
hero_image: images/banner.png
description: Sonic Pi के साथ Raspberry Pi पर कोड संगीत लाइव करना सीखें
original_url: https://raspberrypi.org/learning/getting-started-with-sonic-pi
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: music
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: आपको किन चीज़ों की आवश्यकता होगी
  - 
    title: पहले ध्वनि Sonic Pi के साथ
  - 
    title: एक धुन को लूप करे
  - 
    title: MIDI नोट्स और संगीत नोट्स
  - 
    title: धुन बदलें
  - 
    title: नमूनों का उपयोग करें
  - 
    title: एक ही समय में दो धुन बजाना
  - 
    title: लाइव कोड!
  - 
    title: प्रभाव जोड़ना
  - 
    title: पैरामीटर्स को संशोधित करें
  - 
    title: rrand का उपयोग करना
  - 
    title: आगे क्या?
