---
title: Getting Started With Sonic Pi
hero_image: images/banner.png
description: Learn how to live code music on the Raspberry Pi with Sonic Pi
original_url: https://raspberrypi.org/learning/getting-started-with-sonic-pi
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: music
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: First sounds with Sonic Pi
  - 
    title: Loop a tune
  - 
    title: MIDI notes and music notes
  - 
    title: Change the sounds
  - 
    title: Use samples
  - 
    title: Playing two tunes at the same time
  - 
    title: Live code!
  - 
    title: Adding effects
  - 
    title: Modifying Parameters
  - 
    title: Using rrand
  - 
    title: What next?
