---
title: Erste Schritte mit Sonic Pi
hero_image: images/banner.png
description: Erfahre, wie Du mit Sonic Pi Musik auf dem Raspberry Pi live kodieren kannst
original_url: https://raspberrypi.org/learning/getting-started-with-sonic-pi
theme: Rot
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, Entwurf-0, Programmierung-2, Phys-Komp-0, Herstellung-0, Gemeinschaft-0
interests: Musik
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Erste Sounds mit Sonic Pi
  - 
    title: Wiederhole eine Melodie
    completion:
      - engaged
  - 
    title: MIDI-Noten und Musiknoten
  - 
    title: Ändere die Sounds
  - 
    title: Verwende Samples (Beispiele)
  - 
    title: Zwei Musikstücke gleichzeitig spielen
  - 
    title: Live-Code!
  - 
    title: Effekte hinzufügen
  - 
    title: Parameter ändern
  - 
    title: Rrand verwenden
    completion:
      - internal
  - 
    title: Was kommt als Nächstes?
