---
title: Primeros pasos con Sonic Pi
hero_image: images/banner.png
description: Aprende cómo programar música en vivo en el Raspberry Pi con Sonic Pi
original_url: https://raspberrypi.org/learning/getting-started-with-sonic-pi
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: music
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
  - title: Introducción
  - title: Lo que necesitarás
  - title: Primeros sonidos con Sonic Pi
  - title: Buclear una melodía
  - title: Notas MIDI y notas musicales
  - title: Cambia los sonidos
  - title: Usa otros sonidos grabados
  - title: Reproduce dos melodías al mismo tiempo
  - title: '¡Programa en vivo!'
  - title: Añade efectos
  - title: Modifica parámetros
  - title: Utiliza rrand
  - title: '¿Qué sigue?'
